### ISSUE TITLE
Randomize starting player

### ISSUE THREAD

**Issue by nwolfe** [dougli1sqrd/games#2]
It appears Player X (Computer) always goes first, and always takes the middle.
We should make it randomly select the first player.

**Comment by dougli1sqrd** [comment]
nice. Closing tickets from 3 years ago! This was a fun project

**Comment by nwolfe** [comment]
@dougli1sqrd Haha hey man, almost said "Hi Eric" when I closed this.  Been using the general "Issues" and "Pull Requests" buttons at the top of GitHub more frequently and wanted to trim some cruft.
